# Generated by Django 3.1 on 2023-10-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20231011_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(default='M-Pesa', max_length=100),
        ),
    ]
